# -*- coding: utf-8 -*-
"""License Plate Recognition.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZIJ-aHLgHAhXCdgQZegdlzpVx0ZFw5Op
"""

!pip install ultralytics roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="mBeemtNCzqYZj2MRDcGy")
project = rf.workspace("nivu").project("indian-license-plate-knte7")
version = project.version(1)
dataset = version.download("yolov8")

import os
print(os.listdir('/content/Indian-License-Plate-1'))

from google.colab import drive
drive.mount('/content/drive')

import torch
print("GPU available:", torch.cuda.is_available())
print("GPU name:", torch.cuda.get_device_name(0))

import os

dataset_path = '/content/Indian-License-Plate-1'

print(os.listdir(dataset_path))

from ultralytics import YOLO


model = YOLO('yolov8n.pt')

# Train
model.train(
    data=f'{dataset_path}/data.yaml',
    epochs=50,
    imgsz=640,
    batch=16,
    name='license_plate_detector',
    patience=10,
    save=True,
    plots=True
)

# Show training graphs
from IPython.display import Image
Image('/content/runs/detect/license_plate_detector/results.png')

training_metrics = model.val(split='train')
validation_metrics = model.val(split='val')
test_metrics = model.val(split='test')

def show_metrics(name, metrics):
    print(f"\n{name}")
    print(f"mAP@50      : {metrics.box.map50:.4f}")
    print(f"mAP@50-95   : {metrics.box.map:.4f}")
    print(f"Precision   : {metrics.box.mp:.4f}")
    print(f"Recall      : {metrics.box.mr:.4f}")

show_metrics("Train", training_metrics)
show_metrics("Validation", validation_metrics)
show_metrics("Test", test_metrics)

# Load best trained model
trained_model = YOLO('/content/runs/detect/license_plate_detector/weights/best.pt')

# Convert to TFLite
trained_model.export(format='tflite', imgsz=640)

print("TFLite conversion done!")