# -*- coding: utf-8 -*-
"""License Plate TFLite Conversion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_FyeZFZ0JEaFN283OWnPm53QyoGK-Xll
"""

# from ultralytics import YOLO

# model = YOLO('/content/best.pt')

# print("Model loaded!")

from ultralytics import YOLO

model = YOLO('/content/best.pt')

print("Model Loaded")

model.export(format='tflite', imgsz=640)
print("Export Complete")